// <auto-generated />
using ITTWEB_Assignment_06.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ITTWEBAssignment06.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    [Migration("20171205092527_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exercise", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Workoutid");

                    b.Property<string>("description");

                    b.Property<string>("exercise");

                    b.Property<int>("reps");

                    b.Property<int>("sets");

                    b.HasKey("id");

                    b.HasIndex("Workoutid");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Workout", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("count");

                    b.Property<string>("name");

                    b.HasKey("id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Exercise", b =>
                {
                    b.HasOne("Workout")
                        .WithMany("exercises")
                        .HasForeignKey("Workoutid");
                });
#pragma warning restore 612, 618
        }
    }
}
